### PR TITLE
Add ice crystal diagnostics and make them available in AERmon

### PR DESCRIPTION
**Pull request by plesager**
For the FORCeS project, we have further developed the EC-Earth3-AerChem model to include ice nucleation parameterization among other things. A corresponding set of diagnostics has been implemented and their cmorization is the reason for this PR. In the `ice-nucleation-diag` branch, the grib codes table and the recipes (ifspar.json) have been updated. The `scripts/add-non-cmor-variables.sh` is modified for the user to update the AERmon table.

### CODE REVIEW

**Comment by klauswyser** [comment]
The branch doesn't include [the scaling of reffclis, etc.](https://dev.ec-earth.org/issues/1211#note-14) yet. Shall we do that?

**Comment by plesager** [comment]
Ok, looking at the `ifspar.json`, we only have two Reff expected and Montse confirmed that they are in the wrong units. So we just need this fix:
```
diff --git a/ece2cmor3/resources/ifspar.json b/ece2cmor3/resources/ifspar.json
index e71bbf1..551da5d 100644
--- a/ece2cmor3/resources/ifspar.json
+++ b/ece2cmor3/resources/ifspar.json
@@ -1,11 +1,13 @@
 [
     {
         "source": "21.126",
-        "target": "reffclws"
+        "target": "reffclws",
+        "expr": "var126021*1e-6"
     },
     {
         "source": "24.126",
-        "target": "reffclis"
+        "target": "reffclis",
+        "expr": "var126024*1e-6"
     },
     {
         "source": "30.126",
```
Agree?

**Comment by plesager** [comment]
Well, that did not work:
```
ERROR:ece2cmor3.cmor_source: Expression var126021*1e-6 assigned to reserved existing grib code 21.126, skipping expression assignment
ERROR:ece2cmor3.cmor_source: Expression var126024*1e-6 assigned to reserved existing grib code 24.126, skipping expression assignment
```

**Comment by plesager** [comment]
What we want is to pass `mulc,1e-6` to `cdo`. How can we do that?

**Comment by klauswyser** [comment]
Sorry to tell, but I'm pretty sure that this won't work. (I cannot test right now because our computer is down for maintenance.) The problem is that you try to save the output of ````cdo expr,... ```` to a file with the same name as the inputfile (e.g. 21.126,1,1) and output which will fail. You could save the output as 21.129 instead with this change:
````
     {
         "source": "21.129",
         "target": "reffclws",
         "expr": "var126021*1e-6"
     },
````
This works if 21.129 hasn't been taken already (I don't think so, but please double-check).

Maybe another way to solve this in a more transparent way would be to add a new conversion, say ``div1e6`` and define it in ifs2cmor.py as:
````
    if conversion == "div1e6":
        return 1e-6, 0
````
The corresponding change in ifspar.py would be: 
````
     {
         "source": "21.126",
         "convert": "div1e6",
         "target": "reffclws"
     },
````

**Comment by klauswyser** [comment]
> What we want is to pass `mulc,1e-6` to `cdo`. How can we do that?

Sorry, didn't see your latest post while I was writing on my own post above. I think it explains why your first suggestion doesn't work, and it gives 2 alternatives for what else we could try.

**Comment by plesager** [comment]
@treerink @goord How do you force ece2cmor3 to recognize the changes in `ifspar.json`? Looks like it doesn't see it when I re-cmorize a leg. I am in develop mode (`python setup.py develop`) if that matters.

**Comment by treerink** [comment]
> @treerink @goord How do you force ece2cmor3 to recognize the changes in `ifspar.json`? Looks like it doesn't see it when I re-cmorize a leg. I am in develop mode (`python setup.py develop`) if that matters.

I am not longer using that one but:
`pip install -e .`
for development mode, I don't know whether that matters (I thought not actually).

**Comment by plesager** [comment]
Ok. got it to work. I had a wrong argument in my call to ece2cmor3. The changes in ifspar.json are detected normally.

In 5f374c2 I convert the Reff into meters as requested by CMIP6.

**Pull request merged**
