### PR TITLE
Zonal means

### PR DESCRIPTION
**Pull request by treerink**
This is #500 point 4, which is also mentioned in #542.

### CODE REVIEW

**Comment by fserva** [comment]
Hello @treerink, I have one question related to the CMORization of zonal mean variables. 
You maybe recall that for DynVar (e.g. #481) there are some variables from IFS output, but some also to be calculated 'offline' from the model outputs and then CMORized. 
Most of the variables are in zonal mean form: is it preferred to keep them like (time,lev,lat) or (time,lev,lat,lon) with a single value (say, 0° or 180°) for the longitude dimension?
Thanks

**Comment by goord** [comment]
Hi @fserva I believe it is requested to remove the lon variable + dimension entirely after taking zonal means. Other choices may confuse people thinking they are looking at some transect?

**Comment by fserva** [comment]
Thanks @goord for the suggestion. Yes it is easy for me to save the files like this, I was only wondering if ece2cmor works well with zonal mean input files: are there other zonal mean variables already included? It would be useful to see how they are treated. Thanks!

**Comment by goord** [comment]
Hi @fserva I'm not sure what you mean by zonal means _input_ files, but we recently added support for zonal means _output_ of atmospheric fields, you can test this by including such variables in your varlist (actually, they were already included but ece2cmor3 used to produce errors for them)

**Comment by fserva** [comment]
Yes, I mean _outputs_ of the diagnostics for dynvar and _inputs_ for ece2cmor. I'll check the variables you added then, thanks.

**Comment by treerink** [comment]
See #500 first post point 4, for instance `zg,` `ua` , `va`. And see #578.

**Pull request merged**
