### PR TITLE
Fix ec550aer

### PR DESCRIPTION
**Pull request by tommibergman**
With the new comer 3.5.0 library the EC550aer variable can be processed. Pull request also includes some cleanup and improvements.

### CODE REVIEW

**Comment by tommibergman** [comment]
Now I see that master still has cmor 3.4.0, so please don't pull until cmor is upgraded to 3.5.0.

**Comment by treerink** [comment]
Yes I am aware of that. I am waiting for a fixing release of drq, because it is broken in `01.00.31.` As soon a next `dreq/drq` fixed version is released I will solve #524. Thereafter this `fix-ec550aer` branch can be merged I guess?

**Comment by tommibergman** [comment]
Yes, I think so.

**Comment by treerink** [comment]
Merging this branch should solve #421

**Pull request merged**
