### PR TITLE
add new component co2box

### PR DESCRIPTION
**Pull request by etiennesky**
Hi @treerink @klauswyser this pull request is to add cmorization of co2box model output. Since the data is quite small (about 142kb for one year), I could add some example files to test it.

### CODE REVIEW

**Comment by etiennesky** [comment]
Note that I also added the data request in the optimesm branch.

```
    "co2box": {
        "Amon": [
            "co2mass"
        ],
        "Emon": [
            "co2s"
        ],
        "day": [
            "co2s",
            "co2mass"
        ]
    }
```

the tm5 part needs to be removed because it clashes with co2box

I also need 2 non-standard CMIP6 variables which are co2s and co2mass in the day Table, whereas they are officially only defined in the Amon table.  Here is the what I added to my local tables in CMIP6_day.json

```
       "co2s": {
            "frequency": "day",
            "modeling_realm": "atmos",
            "standard_name": "mole_fraction_of_carbon_dioxide_in_air",
            "units": "1e-06",
            "cell_methods": "time: mean",
            "cell_measures": "area: areacella",
            "long_name": "Atmosphere CO2",
            "comment": "As co2, but only at the surface",
            "dimensions": "longitude latitude time",
            "out_name": "co2s",
            "type": "real",
            "positive": "",
            "valid_min": "",
            "valid_max": "",
            "ok_min_mean_abs": "",
            "ok_max_mean_abs": ""
        },
       "co2s": {
            "frequency": "day",
            "modeling_realm": "atmos",
            "standard_name": "mole_fraction_of_carbon_dioxide_in_air",
            "units": "1e-06",
            "cell_methods": "time: mean",
            "cell_measures": "area: areacella",
            "long_name": "Atmosphere CO2",
            "comment": "As co2, but only at the surface",
            "dimensions": "longitude latitude time",
            "out_name": "co2s",
            "type": "real",
            "positive": "",
            "valid_min": "",
            "valid_max": "",
            "ok_min_mean_abs": "",
            "ok_max_mean_abs": ""
        },
```

**Comment by treerink** [comment]
Hi Etienne, I see `co2s` twice as add to  the `CMIP6_day.json` table, probably the second one should be `co2mass`. Could you post them one time more?

**Comment by etiennesky** [comment]
> Hi Etienne, I see `co2s` twice as add to the `CMIP6_day.json` table, probably the second one should be `co2mass`. Could you post them one time more?

fixed

**Comment by etiennesky** [comment]
is there a place I can add test data? is that in the b2share folder?

also, do  I update the json data request for optimesm with new co2box component?

**Comment by etiennesky** [comment]
@treerink test data can be found on ECFS ec:/c3et/EC-EARTH/INPUT/ece2cmor3

**Comment by treerink** [comment]
> @treerink test data can be found on ECFS ec:/c3et/EC-EARTH/INPUT/ece2cmor3

Found it

**Comment by treerink** [comment]
> is there a place I can add test data? is that in the b2share folder?
I will have a look what is best

> also, do I update the json data request for optimesm with new co2box component?
I will take over, but I need a bit of time to get all in the right order. I first will test whether I can immediately add this `genecec` part in the master without breaking anything, that would make the steps easier.

**Comment by treerink** [comment]
@etiennesky any idea why the pytest fails for the co2box branch? I have not investigated yet.

**Comment by etiennesky** [comment]
> > is there a place I can add test data? is that in the b2share folder?
> > I will have a look what is best
> 
> > also, do I update the json data request for optimesm with new co2box component?
> > I will take over, but I need a bit of time to get all in the right order. I first will test whether I can immediately add this `genecec` part in the master without breaking anything, that would make the steps easier.

the "issue" is that co2s and co2mass cannot be defined for both tm5 and co2box in the json file. As we won't have tm5 running in this project it can be removed entirely IMHO

**Comment by etiennesky** [comment]
> @etiennesky any idea why the pytest fails for the co2box branch? I have not investigated yet.

I have no idea, it looks like a very basic problem unrelated to my changes ?

**Comment by treerink** [comment]
Probably you saw that I added in 4aecbc0 in the co2box branch the small script to add the two non-cmor co2box variables in the CMOR day table.

**Comment by etiennesky** [comment]
> > @etiennesky any idea why the pytest fails for the co2box branch? I have not investigated yet.
> 
> I have no idea, it looks like a very basic problem unrelated to my changes ?

ModuleNotFoundError: No module named 'cmor_utils'

maybe there is something in cmor_utils that break it ? The change there is just a new function...

**Comment by treerink** [comment]
> > > also, do I update the json data request for optimesm with new co2box component?
> > > I will take over, but I need a bit of time to get all in the right order. I first will test whether I can immediately add this `genecec` part in the master without breaking anything, that would make the steps easier.
> 
> the "issue" is that co2s and co2mass cannot be defined for both tm5 and co2box in the json file. As we won't have tm5 running in this project it can be removed entirely IMHO

Well I actually think there will be no conflict because the `add-variables-for-co2box.sh` script add the co2box ones to the table and do thus not match with the only official available (potential TM5) table-var combinations:
```
Emon co2s
Amon co2mass
```

**Comment by etiennesky** [comment]
> Well I actually think there will be no conflict because the `add-variables-for-co2box.sh` script add the co2box ones to the table and do thus not match with the only official available (potential TM5) table-var combinations:

There is an issue because we also want official Emon/co2s and Amon/co2mass from the co2box model, not from TM5.  You can see I added them to the optimesm data request json file.

**Comment by treerink** [comment]
> There is an issue because we also want official Emon/co2s and Amon/co2mass from the co2box model, not from TM5. You can see I added them to the optimesm data request json file.

Ah yes I see (I saved it locally before overwriting it). Ok clear, best is to organise this in the preference file. I will have a look, but first I want to solve the LPJG .ins part now.

**Comment by treerink** [comment]
Ok 621c2df was a fix to enable to run `genecec` in the co2box branch, it also fixes the pytest locally and here at the github.

**Comment by treerink** [comment]
#785 implemented and merged into the master.

**Pull request merged**
